<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://unpkg.com/pagedjs@0.4.0/dist/paged.polyfill.js"></script>
    <link rel="stylesheet" href="interface.css">
    <style>
        @page {
            size: A5;
            bleed: 6mm;
            margin:10mm;
            text-align:justify;
            marks: crop;
            @bottom-left {
                content: counter(page);
            }
        }
    </style>
</head>
<body>
    ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpaR1d3aGdhbWFod21uVlgxMlFVeW1I@185.88.140.44:40181/?outline=1
    <p>
        What they were doing there,
	They were both, after this season of binary monologues, wrapped in cold, rough emotions. They stood there, bickering, certainly to revisit the complicity of their gestures. In their course, the alternated blows and laughs. They made a stop to glance over the horizon. “The blue of the sky is duller than that of the sea”. He did not listen to her. She turned her head and realized that he was silently gazing the crashing of the waves, collapsing at the foot of the lighthouse. She noted that the icy air tinted her cheekbone pink. In a brief gesture, she pinched his cheek, as she might have done to a child. Surprised, he caught her hard wrist in flight. She struggled with a smile hanging on her lip. But, with finesse, he successfully reached he little finger, as she hated so much. “Ouch. You’re so annoying, we can never enjoy the scenery with you” she said. In a calm tone, he replied: “You’re absurd”. Then, he took her round face in his frail hands. He looked at her a moment, before bringing his mouth close to hers/ “Patriarcho,” she called out him as she pulled her head free from his hands. “You call me absurd and you want me to kiss your lips?”. She began to walk with quick steps. He grabs her by the arm. She stopped short. “I’ve always liked absurdity”. As if she hadn’t heard him, she said insistently, “Look, it look like the sun is coming out.” “Come on,” he said “Do we walk to the cliffs? Yes”. So, they did, jerkily along to the taste of their teasing. The relentless sea sang aloud its eternal chorus. His hair blowing in the wind, he wobbled because of the pebbles. She took his hand. Then, lifting her head, she smiled when she noticed a girl lying a few meters above. Tired of the icy weather and the difficulties of the route, he said to her without much conviction: “Some people think it’s summer.” She couldn’t help but reply “that he’s just a killjoy”. 
	A few hours later, she thought of the girl she saw lying on the beach. They were on the train back home. She was watching the landscape passing before her eyes. As for him, he was dozing, his head against his shoulder, his slender legs stretched out along the aisle.
"Maybe she lives around here." she thought. But something made her want to believe that she was just passing by. Certainly, this instinct of clairvoyance was only the result of her own desire, that through this memory she could look at their situation from a distance. It’s true that it had been a long time since she had last thought about her independently of him. Her thoughts wandered in that direction. Particularly, towards that evening when she had left her small studio on a whim to let herself be carried away by the chance of night's game. Faces flashed through her mind, memories that were still fresh, if a little fickle. Above all, the adrenaline that was in her. The fear she felt while cycling through the dark streets. Alone. That word resonated like the crashing of the waves at the foot of the lighthouse. It was not that her life depended materially on the other. In fact, what upset her was that this kind of crazy idea no longer occurred to her: to leave for a drink at the other end of the city, to meet up with this friend or that acquaintance, to go to parties in Barbès or to techno clubs in the 19th, alone. This type of desire was mortified by the arrival of the other and his love. To remember of telling him where she was, what she was doing, with whom, at first just so that he could get to know her life better, and indeed her person. Now, these smalltalk have become a usual mark to reassure. "To reassure who exactly?" she wondered. She wasn't quite sure if he would sink into a sense of dread if she didn't text him one night. She tacitly shook his shoulder and said, "Is it part of our love to look out for each other and therefore tell each other where we are? Is it possible to love each other without knowing where we are? 
- You have such questions when you wake up...
- No, but it's very simple, listen, would it upset you if I didn't write to you anymore to tell you where I am?   
- Why do you want to talk about things that are supposed to be upsetting, that aren't even happening?
- Think about it, there's a wider scope to what I mean.
He straightened up to tousle the short brown curls on the small round head in front of him with a wave of his hand. She blushed. "I think I need a more concrete example to answer your question.
- Let's say I leave tomorrow, alone in ... Cambodia, without telling you where I am, will you still love me?
- It all depends on your intentions.
- What if you have no way of knowing them?"
He ran his hand through his long golden curls this time, "I think if you're leaving, I'd like you to tell me why. I don't care where you go as long as you know what takes you there."
She rested her head limply against his shoulder. He put his arm around her and held her tight. His eyes watered from imagining himself in such a situation. But he remained silent about his emotions. As for her, she had the feeling that something was missing. It was as if the response he gave answer her question without grasping it. She would have liked to continue speaking but the words wouldn’t come. She could only hear his silence. That was how it was, they only had words to understand each other, and sometimes their meaning stayed this way, a little abstract. If only he had told her that the mere fact that she was inventing this scenario made him sad, probably the situation would have been quite different. But, in his bashfulness resides a part of mystery, that he didn't know how to express. So, without doubt, the essence of their love was hidden in this shadowy corner, around which each of them tried to situate themselves, without ever quite succeeding.

She was sitting on the terrace of a café on boulevard Ménilmontant. It had been a few days or a few weeks since she had returned from her escapade at the sea. In reality, this escape was organized in the grip of a sudden feeling. Carried away by it, she had taken a train ticket the same day. Just like that. To catch some fresh air. A need to empty her lungs of the toxins she stores daily. Now, she was waiting at the café for a friend to come. But, all in all, she didn't care if she came or not. She was alone, with a pile of second-hand books on the table. She herself was immersed in reading a book, a complex history of Lebanon. She was half-dreaming, about the sentences of her economics teacher, that she hated, the morning theft of a handbag that she had witnessed in T1 and then about that couple she had seen the last time walking on the beach. Suddenly, she looked up from her book to see the bustle of the boulevard. She saw the continuous parade of cars, passers-by at full speed, lawless people on the phone crossing the road as it suited them, armed cyclists intervening, making their way half on the sidewalk, half on the road, and a few garbage floating here and there between sky and earth. In short, Paris in its multitude she thought. It was not her district the twentieth, but the bars were not that expensive, there’s that, no more explanation. She looked at the time on her phone: five to eight. She was surprised that she already had been here for quite some time.  This discovery made her feel worried about whether her friend would show up or not. She thought to herself that it would be a bit sad to start her weekend alone in a café reading things that didn't make sense anymore. That's the problem with being alone, she thought. You go from one mood to another and when you think you're happy you become sad. She took another sip of the Côte de Provence and ironically wondered when she had started to enjoy drinking wine. It was the café terrace effect, no doubt. She would have taken a Chablis but it’s too expensive, a Chardonnay is too common. “Not at all, I just come from an exhibition, not from the cinema...” She began to listen to the two women at the next table. Immediately, she said to herself that this was a date. At least, that's what she imagined; no heard information proved it. They just seemed, according to her, to devour each other with their eyes. Specially, to speak to each other so that they are not interested in anything else than the present moment that passed before their eyes. 
She knew that it could also be a couple with long years behind them. But she rejected this idea because for her, once we’re settled we stopped going to the café. It’s only in the beginning of a relation that we could make us believe we’ll waste time together. After that, everyday life swipes everything without any bother, surely until the next date. With such fixed ideas about couples, she was bound to think that the lovers at the beach the other day were not seeing each other for much more than three months. A blooming love, no more or less. “Tartine de vie… a podcast you should listen to.”, she was also listening to this one. Anyway, there was a paradox in her, that she never pinpointed in years. Everytime, she believed to touch it and pop it for good. She was just pinching it with the tip of her fingers, and it just flew even more so. No, nothing to do about it. She couldn’t grasp her consuming passion for relationships without the desire to live one. She had the taste of it, like a child fixing the showcase of a bakery but that never dare to enter, scared of saying good morning. As if her conception of relationships, maybe too passionate, constantly kept her away from the nature of love and only let her contemplate it from afar. The weather turned heavy. Her friend was on her way but was not showing up. She quit the bar, books in her hands. 

    </p>
</body>
</html>